image: Dockerfile

# Puertos a exponer al workspace
ports:
  - port: 3000
    onOpen: ignore
  - port: 8080
    onOpen: ignore

# Tareas a ejecutar antes de iniciar el workspace
tasks:
  - init: |
      echo "Iniciando entorno Arch Linux"
      # Aquí puedes agregar comandos de inicialización
    command: |
      echo "Workspace listo!"

# Extensiones para instalar
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cmake-tools
    - twxs.cmake
    - cschlosser.doxdocgen
    - jeff-hykin.better-cpp-syntax
    - ms-vscode.cpptools-themes
    - vadimcn.vscode-lldb
    - esbenp.prettier-vscode
    - formulahendry.code-runner
    - PKief.material-icon-theme
    - eamodio.gitlens
    - aaron-bond.better-comments
    - oderwat.indent-rainbow
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.jupyter-keymap
    - dracula-theme.theme-dracula

# Protección para GitHub
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false

# Configuración de git
gitConfig:
  protect:
    - .gitpod.yml
    - Dockerfile
    - README.md
