image:
  file: Dockerfile

# Puertos
ports:
  - port: 3000
    onOpen: ignore
  - port: 8888
    onOpen: ignore

# VS Code
vscode:
  extensions:
    - ms-vscode.cpptools
    - ms-vscode.cmake-tools
    - twxs.cmake
    - ms-python.python
    - ms-toolsai.jupyter
  settings:
    terminal.integrated.shell.linux: /bin/bash
    editor.fontSize: 14
    editor.fontLigatures: true
    workbench.colorTheme: Dracula