image:
  file: Dockerfile

# Ports to expose to the workspace
ports:
  - port: 3000
    onOpen: ignore
  - port: 8080
    onOpen: ignore

# Tasks to run before starting the workspace
tasks:
  - init: |
      echo "Iniciando entorno Arch Linux"
    command: |
      echo "Workspace listo!"
      pip install ipython-cpp
      
# Extensions to install
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cmake-tools
    - twxs.cmake
    - cschlosser.doxdocgen
    - jeff-hykin.better-cpp-syntax
    - ms-vscode.cpptools-themes
    - vadimcn.vscode-lldb
    - esbenp.prettier-vscode
    - formulahendry.code-runner
    - PKief.material-icon-theme
    - eamodio.gitlens
    - aaron-bond.better-comments
    - oderwat.indent-rainbow
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.jupyter-keymap
    - dracula-theme.theme-dracula
